services:
  sync:
    image: tomaslobato/sync
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ${FOLDER}:/app/files
    environment:
      - FOLDER=/app/files
    restart: unless-stopped
